[package]
name = "chip8"
version = "0.1.0"
authors = ["Taylor Thurlow <taylorthurlow@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "chip8"
path = "src/main.rs"
